#!/bin/bash
#ddev-generated
## Description: Run bosa_a11y checker
## Usage: bosa_a11y [args]
## Example: "ddev bosa_a11y https://www.example.be/"
## ExecRaw: true

output=$(docker exec ddev-${DDEV_PROJECT}-bosa-a11y node bosa.js "$@")
SUBSTRING=`echo $output | cut -d "@" -f2 | cut -d "@" -f1`

case $OSTYPE in
  linux-gnu)
    if [ -n "$WSL_DISTRO_NAME" ]; then
      explorer.exe "$(wslpath -w $PWD/reports/bosa_a11y/results/${SUBSTRING})"
    else
      xdg-open ${DDEV_APPROOT}/reports/bosa_a11y/results/${SUBSTRING}
    fi
    ;;
  "darwin"*)
    open ${DDEV_APPROOT}/reports/bosa_a11y/results/${SUBSTRING}
    ;;
  "win*"* | "msys"*)
    start ${DDEV_APPROOT}/reports/bosa_a11y/results/${SUBSTRING}
    ;;
esac
